### PR TITLE
Implement ranging correction algorithm from #105.

### PR DESCRIPTION
**Pull request by jonathanpallant**
This could do with some tidying up, but does it look like I've broadly understood the concept?

### CODE REVIEW

**Comment by hannobraun** [comment]
Thank you for the pull request! I didn't check all the numbers, but this looks roughly right to me!

There's one problem though: The bias values given in #105 are specific to the DWM1001 (the board) and might be different for another board using the DW1000 (the chip). So the changes can't be just added to the function in `dw1000`. The issue wasn't very clear about that; sorry!

I can think of two solutions:
1. Leave the function in `dw1000` unchanged, provide a wrapper (possible for the whole module) in `dwm1001`.
2. Add some means to plug the correction value tables into the function in `dw1000`, but define those tables in `dwm1001`. For ease of use, a wrapper could still be added.

I'd be fine with both solutions. Solution 2 would probably make it more obvious to users that correction is required for good results.

Did you test it with the correction values? Do they provide good accuracy?

**Comment by jonathanpallant** [comment]
I'd need to run some repeatable tests, as I've only been waving two around with one in each hand so far. But it didn't look a million miles out.

I'll build a CalibrationTables trait that can be plugged in, and put an impl in the DWM1001C crate.

**Comment by hannobraun** [comment]
Looks like this was closed accidentally in #145. I guess it can stay closed though, as this has been inactive for a long time.

**Comment by jkelleyrtp** [comment]
I have a local branch with these features wired up, will make a PR soon.

**Pull request closed without merging**
