### PR TITLE
Move the future methods to the main object to allow for async behavior

### PR DESCRIPTION
**Pull request by jamesmunns**
Without these changes, it is difficult to develop a non-blocking interface without having a self-referential struct.

### CODE REVIEW

**Comment by hannobraun** [comment]
Man, somehow I always forget about self-referential structs :-)

So, to clarify: This solves the problem by allowing the caller to drop the future, then use `DW1000` directly instead, am I right? If so, it would be nice to add a sentence or two to the documentation of the new `DW1000` methods, to explain that's the reason they exist.

This doesn't seem very elegant to me, but I'm inclined to merge it, unless we can come up with a better solution quickly. I wonder if [`Pin`](https://doc.rust-lang.org/std/pin/struct.Pin.html) could be used to make the current pattern work instead. Not sure though, as I haven't used it yet.

What do you think?

**Comment by jamesmunns** [comment]
I'm also not too familiar with how Pin works in practice.

I'm okay to keep this open for now, I'm working on some code where I actually use this, so lets see if it works effectively in practice. I agree the comments could be improved as well.

**Comment by hannobraun** [comment]
Two notes:
1. I've had a chance to look into `Pin` in another project and found both understanding and using it quite challenging. I ended up going with another solution for my problem. Not a final verdict, but a data point.
2. What if we moved `DW1000` instead of borrowing it? In that case it would probably make sense to remove `TxFuture`/`RxFuture` and go for `DW1000<Sending>`, `DW1000<Receiving>` instead.

To elaborate on the second item, that would mean we'd have an `fn send(self, ...) -> DW1000<Sending>`. If `DW1000` lives in a struct, you could wrap it in something like this:
``` rust
enum DW1000State {
    Standby(DW1000<Enabled>),
    Sending(DW1000<Sending>),
    Receiving(DW1000<Receiving>),
}
```

Does that sound reasonable?

**Comment by hannobraun** [comment]
Superseded by #93. I'm closing this for now, but we might want to come back to this approach, if #93 doesn't work out and has to be reverted.

**Pull request closed without merging**
